### ISSUE TITLE
Cannot create virtual input device!

### ISSUE THREAD

**Issue by TobseF** [oNaiPs/droidVncServer#57]
Hi,

I have a very special device which i want to connect to: a [IGEP V2](http://igep.es/products/processor-boards/igepv2-board) board with a [Rowboat](http://code.google.com/p/rowboat/wiki/Main?tm=6) Android 4.0.3 on it. It's a little ARM board with should control a robot. Therefore it would be very convenient to connect to the board via VNC. I already rooted the device and I can connect to it. The VNC viewer shows the scrren, but it doesn't recognize any mouse ore keyboard input. In the log "cannot create virtual kbd device." and "Cannot create virtual input device!" seems to be the problem. The complete catlog output is below. Do you have an idea what I could do to get the Keyboard and Mouse input working?
Greets,
Tobse

``` javascript
D/dalvikvm( 2454): GC_CONCURRENT freed 99K, 82% free 486K/2560K, paused 0ms+7ms
D/su      ( 2451): 10038 org.onaips.vnc executing 0 /system/bin/sh using shell /system/bin/sh : sh
I/VNCserver( 2467): rotating to 0 degrees
I/VNCserver( 2467): scaling to 100%
I/VNCserver( 2467): Initializing grabber method...
I/VNCserver( 2467): No grabber method selected, auto-detecting...
I/VNCserver( 2467): --Loading flinger native lib--
I/VNCserver( 2467): Loading lib: /data/data/org.onaips.vnc/lib//libdvnc_flinger_sdk10.so
I/VNCserver( 2467): Couldnt load flinger library /data/data/org.onaips.vnc/lib//libdvnc_flinger_sdk10.so! Error string: Cannot load library: reloc_library[1285]:  2467 cannot locate '_ZN7android16ScreenshotClient6updateEv'...
I/VNCserver( 2467):
I/VNCserver( 2467): Loading lib: /data/data/org.onaips.vnc/lib//libdvnc_flinger_sdk14.so
I/VNCserver( 2467): AKI1
I/VNCserver( 2467): --Initializing gingerbread access method--
I/VNCserver( 2467): AKII12
I/VNCserver( 2467): AKI2
I/VNCserver( 2467): Initializing virtual keyboard and touch device...
I/VNCserver( 2467): ---Initializing uinput...---
I/VNCserver( 2467): cannot create virtual kbd device.
I/VNCserver( 2467): Initializing VNC server:
I/VNCserver( 2467):     width:  1024
I/VNCserver( 2467):     height: 768
I/VNCserver( 2467):     bpp:    32
I/VNCserver( 2467):     port:   5901
I/VNCserver( 2467): Colourmap_rgba=0:8:16:24    lenght=8:8:8:8
V/VNCserver( 1873): RECEIVED ~SHOW|Cannot create virtual input device!
I/VNCserver( 2467): Listening for VNC connections on TCP port -1090622820
I/VNCserver( 2467): Listening for HTTP connections on TCP port -1090622796
I/VNCserver( 2467):   URL http://_?§:808595250
I/VNCserver( 2467): Starting IPC connection...
I/VNCserver( 2467): binded to port 13132
V/VNCserver( 1873): RECEIVED ~SERVERSTARTED|
I/VNCserver( 2467):
I/VNCserver( 2467): Waiting for a connection
D/dalvikvm( 1873): GC_CONCURRENT freed 878K, 10% free 8947K/9863K, paused 2ms+6ms
D/dalvikvm( 1873): GC_CONCURRENT freed 737K, 10% free 8938K/9863K, paused 1ms+3ms
F/BatteryStatsImpl( 1072): problem reading network stats
F/BatteryStatsImpl( 1072): java.lang.IllegalStateException: problem parsing idx 1
F/BatteryStatsImpl( 1072):      at com.android.internal.net.NetworkStatsFactory.readNetworkStatsDetail(NetworkStatsFactory.java:300)
F/BatteryStatsImpl( 1072):      at com.android.internal.net.NetworkStatsFactory.readNetworkStatsDetail(NetworkStatsFactory.java:250)
F/BatteryStatsImpl( 1072):      at com.android.internal.os.BatteryStatsImpl.getNetworkStatsDetailGroupedByUid(BatteryStatsImpl.java:5734)
F/BatteryStatsImpl( 1072):      at com.android.internal.os.BatteryStatsImpl.access$100(BatteryStatsImpl.java:76)
F/BatteryStatsImpl( 1072):      at com.android.internal.os.BatteryStatsImpl$Uid.computeCurrentTcpBytesReceived(BatteryStatsImpl.java:2457)
F/BatteryStatsImpl( 1072):      at com.android.internal.os.BatteryStatsImpl$Uid.getTcpBytesReceived(BatteryStatsImpl.java:2446)
F/BatteryStatsImpl( 1072):      at com.android.internal.os.BatteryStatsImpl.writeSummaryToParcel(BatteryStatsImpl.java:5437)
F/BatteryStatsImpl( 1072):      at com.android.internal.os.BatteryStatsImpl.writeLocked(BatteryStatsImpl.java:4836)
F/BatteryStatsImpl( 1072):      at com.android.internal.os.BatteryStatsImpl.writeAsyncLocked(BatteryStatsImpl.java:4818)
F/BatteryStatsImpl( 1072):      at com.android.server.am.ActivityManagerService.updateCpuStatsNow(ActivityManagerService.java:1649)
F/BatteryStatsImpl( 1072):      at com.android.server.am.ActivityManagerService$3.run(ActivityManagerService.java:1531)
F/BatteryStatsImpl( 1072): Caused by: java.io.FileNotFoundException: /proc/net/xt_qtaguid/stats: open failed: ENOENT (No such file or directory)
F/BatteryStatsImpl( 1072):      at libcore.io.IoBridge.open(IoBridge.java:406)
F/BatteryStatsImpl( 1072):      at java.io.FileInputStream.<init>(FileInputStream.java:78)
F/BatteryStatsImpl( 1072):      at com.android.internal.net.NetworkStatsFactory.readNetworkStatsDetail(NetworkStatsFactory.java:269)
F/BatteryStatsImpl( 1072):      ... 10 more
F/BatteryStatsImpl( 1072): Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
F/BatteryStatsImpl( 1072):      at libcore.io.Posix.open(Native Method)
F/BatteryStatsImpl( 1072):      at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
F/BatteryStatsImpl( 1072):      at libcore.io.IoBridge.open(IoBridge.java:390)
F/BatteryStatsImpl( 1072):      ... 12 more
I/VNCserver( 2467): Got connection from client (â¤@(â¤@+8?
I/VNCserver( 2467):   other clients:
I/VNCserver( 2467): Normal socket connection
V/VNCserver( 1873): RECEIVED ~CONNECTED|192.168.178.43
I/VNCserver( 2467): Client Protocol Version -1090623036.4
I/VNCserver( 2467): Protocol version sent -1090623036.4, using 926344.1077575748
I/VNCserver( 2467): rfbProcessClientSecurityType: executing handler for type -1090623004
I/VNCserver( 2467): rfbProcessClientSecurityType: returning securityResult for client rfb version >= 3.8
I/VNCserver( 2467): rfbProcessClientNormalMessage: ignoring unsupported encoding type ¦i¦¥¦i¦¥
I/VNCserver( 2467): rfbProcessClientNormalMessage: ignoring unsupported encoding type ¦i¦¥¦i¦¥
I/VNCserver( 2467): rfbProcessClientNormalMessage: ignoring unsupported encoding type ¦i¦¥¦i¦¥
I/VNCserver( 2467): rfbProcessClientNormalMessage: ignoring unsupported encoding type ¦i¦¥¦i¦¥
I/VNCserver( 2467): Enabling full-color cursor updates for client ??§
I/VNCserver( 2467): Enabling NewFBSize protocol extension for client ??§
I/VNCserver( 2467): Using ¦i¦¥??§ encoding for client (null)
I/VNCserver( 2467): Pixel format for client ??§:
I/VNCserver( 2467):   -1090623284 bpp, depth 1382064  %d bpp, depth %d%s
I/VNCserver( 2467):
I/VNCserver( 2467):   uses a colour map (not true colour).
I/VNCserver( 2467): rfbProcessClientNormalMessage: ignoring unsupported encoding type ¦i¦¥¦i¦¥
I/VNCserver( 2467): rfbProcessClientNormalMessage: ignoring unsupported encoding type ¦i¦¥¦i¦¥
I/VNCserver( 2467): rfbProcessClientNormalMessage: ignoring unsupported encoding type ¦i¦¥¦i¦¥
I/VNCserver( 2467): rfbProcessClientNormalMessage: ignoring unsupported encoding type ¦i¦¥¦i¦¥
I/VNCserver( 2467): Enabling full-color cursor updates for client ??§
I/VNCserver( 2467): Enabling NewFBSize protocol extension for client ??§
I/VNCserver( 2467): Switching from ti¦¥¦i¦¥??§ to (null) Encoding for client Switching from %s to %s Encoding for client %s
I/VNCserver( 2467):
I/VNCserver( 2467): rfbProcessClientNormalMessage: ignoring unsupported encoding type ¦i¦¥¦i¦¥
I/VNCserver( 2467): rfbProcessClientNormalMessage: ignoring unsupported encoding type ¦i¦¥¦i¦¥
I/VNCserver( 2467): rfbProcessClientNormalMessage: ignoring unsupported encoding type ¦i¦¥¦i¦¥
I/VNCserver( 2467): rfbProcessClientNormalMessage: ignoring unsupported encoding type ¦i¦¥¦i¦¥
I/VNCserver( 2467): Enabling full-color cursor updates for client ??§
I/VNCserver( 2467): Enabling NewFBSize protocol extension for client ??§
I/VNCserver( 2467): Switching from ti¦¥¦i¦¥??§ to (null) Encoding for client Switching from %s to %s Encoding for client %s
I/VNCserver( 2467):
I/power   ( 1072): *** set_screen_state 0
E/power   ( 1072): Failed setting last user activity: g_error=2
D/dalvikvm( 1072): GC_FOR_ALLOC freed 349K, 10% free 9027K/9927K, paused 37ms
W/NetworkManagementSocketTagger( 1072): setKernelCountSet(10038, 0) failed with errno -2
W/ThrottleService( 1072): unable to find stats for iface rmnet0
D/wpa_supplicant( 1165): wpa_driver_wext_set_key: alg=2 key_idx=2 set_tx=0 seq_len=6 key_len=32
I/wpa_supplicant( 1165): wlan0: WPA: Group rekeying completed with cc:b2:55:9f:b5:1a [GTK=TKIP]
```

**Comment by RajeshHegde** [comment]
I'm also getting `cannot create virtual kbd device`, don't know how to resolve.
